"""
AutoMLE Kaggle Competition Setup
=================================
Orchestrates: auth -> fetch competition info -> download data -> inspect schema -> generate baseline.

The baseline model is NOT a generic template. It is either:
  (a) written by a human who understands the competition, or
  (b) generated by an AI after reading the competition overview and data schema.

The AI's approach is chosen per-competition based on problem type, metric, and domain
knowledge — not defaulted to sklearn/XGBoost.

Usage:
    # Default — Anthropic Claude (requires ANTHROPIC_API_KEY)
    python -m kaggle.setup --competition titanic
    python -m kaggle.setup --competition house-prices-advanced-regression-techniques
    python -m kaggle.setup --competition titanic --output-dir data/titanic --skip-baseline
    python -m kaggle.setup --competition titanic --skip-download  # use existing data/

    # OpenAI (requires OPENAI_API_KEY)
    python -m kaggle.setup --competition titanic --ai-provider openai
    python -m kaggle.setup --competition titanic --ai-provider openai --ai-model o3-mini

    # OpenAI-compatible cloud (Groq, Together, etc.)
    python -m kaggle.setup --competition titanic \\
        --ai-base-url https://api.groq.com/openai/v1 \\
        --ai-model llama-3.3-70b-versatile

    # Local server — Ollama (no API key required)
    python -m kaggle.setup --competition titanic \\
        --ai-base-url http://localhost:11434/v1 \\
        --ai-model llama3.2 \\
        --ai-api-key local

    # Local server — LM Studio
    python -m kaggle.setup --competition titanic \\
        --ai-base-url http://localhost:1234/v1 \\
        --ai-model local-model

Output structure:
    <output-dir>/
    ├── competition_info.json   # title, description, metric, file list
    ├── data_schema.json        # column types, missing rates, sample values
    ├── data/                   # downloaded train.csv, test.csv, ...
    └── baseline/
        ├── baseline.py         # competition-specific model (approach chosen by the AI)
        ├── data.py             # AutoMLE data module (text framing for LLM fine-tuning)
        ├── evaluator.py        # AutoMLE evaluator module
        ├── _reasoning.txt      # AI's analysis of the competition before coding
        └── _ai_response.txt    # full raw response from the AI

After setup, run the AutoMLE LoRA loop with:
    python run.py \\
        --key <slug> \\
        --checkpoint <model_id> \\
        --data-file <output-dir>/baseline/data.py \\
        --evaluator-file <output-dir>/baseline/evaluator.py
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path


def _sep(title: str = "") -> None:
    bar = "=" * 62
    if title:
        print(f"\n{bar}\n  {title}\n{bar}")
    else:
        print(bar)


def main(argv=None) -> None:
    p = argparse.ArgumentParser(
        description="Set up an AutoMLE task from a Kaggle competition.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--competition", required=True,
        help="Kaggle competition slug, e.g. 'titanic' or 'house-prices-advanced-regression-techniques'.",
    )
    p.add_argument(
        "--output-dir", default=None,
        help="Root directory for all outputs. Defaults to kaggle/tasks/<competition>.",
    )
    p.add_argument(
        "--skip-download", action="store_true",
        help="Skip downloading data (reuse existing files in <output-dir>/data/).",
    )
    p.add_argument(
        "--skip-baseline", action="store_true",
        help="Skip AI baseline generation (fetch + inspect only).",
    )

    ai = p.add_argument_group("AI provider options")
    ai.add_argument(
        "--ai-provider", default="anthropic", choices=["anthropic", "openai"],
        help=(
            "AI provider for baseline generation (default: anthropic). "
            "'openai' covers OpenAI and any OpenAI-compatible API "
            "(Groq, Together, Ollama, LM Studio, etc.)."
        ),
    )
    ai.add_argument(
        "--ai-model", default=None,
        help=(
            "Model name to use. "
            "Defaults: anthropic → claude-sonnet-4-6, openai → gpt-4o."
        ),
    )
    ai.add_argument(
        "--ai-base-url", default=None,
        metavar="URL",
        help=(
            "Base URL for an OpenAI-compatible endpoint. "
            "Examples: http://localhost:11434/v1 (Ollama), "
            "http://localhost:1234/v1 (LM Studio), "
            "https://api.groq.com/openai/v1 (Groq). "
            "Setting this implies --ai-provider openai."
        ),
    )
    ai.add_argument(
        "--ai-api-key", default=None,
        metavar="KEY",
        help=(
            "API key override. "
            "Defaults: ANTHROPIC_API_KEY or OPENAI_API_KEY env var. "
            "For local servers without auth, pass any non-empty string (e.g. 'local')."
        ),
    )

    args = p.parse_args(argv)

    # --ai-base-url implies openai provider
    if args.ai_base_url and args.ai_provider == "anthropic":
        args.ai_provider = "openai"

    slug = args.competition
    root = Path(args.output_dir or f"kaggle/tasks/{slug}")
    data_dir = root / "data"

    _sep(f"Kaggle → AutoMLE : {slug}")
    print(f"  Output root : {root.resolve()}")

    # ------------------------------------------------------------------
    # Step 1: Verify Kaggle credentials
    # ------------------------------------------------------------------
    print("\n[1/4] Checking Kaggle credentials...")
    try:
        from kaggle.auth import load_credentials, is_access_token  # type: ignore[import]
        creds = load_credentials()
        token_type = "Access Token" if is_access_token() else "API key"
        user = creds.get("username", creds["key"][:12] + "...")
        print(f"  OK — {token_type} loaded (user: {user})")
    except (FileNotFoundError, ValueError) as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------
    # Step 2: Fetch competition info
    # ------------------------------------------------------------------
    print("\n[2/4] Fetching competition info from Kaggle API...")
    try:
        from kaggle.fetcher import get_competition_info  # type: ignore[import]
        info = get_competition_info(slug)
    except (PermissionError, ValueError) as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"[error] Unexpected error fetching competition info: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"  Title  : {info['title']}")
    print(f"  Metric : {info['evaluation_metric']}")
    print(f"  Files  : {[f['name'] for f in info['files']]}")
    if not info.get("user_has_entered"):
        print(f"\n  [!] You have not accepted the competition rules yet.")
        print(f"      Visit {info['competition_url']}/rules and click")
        print(f"      'I Understand and Accept' before downloading data.\n")

    root.mkdir(parents=True, exist_ok=True)
    info_path = root / "competition_info.json"
    info_path.write_text(json.dumps(info, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  Saved  → {info_path}")

    # Print overview excerpt so the user can spot-check
    desc_preview = info["description"][:500].replace("\n", " ")
    if len(info["description"]) > 500:
        desc_preview += " …"
    print(f"\n  Overview excerpt:\n    {desc_preview}\n")

    # ------------------------------------------------------------------
    # Step 3: Download data
    # ------------------------------------------------------------------
    if not args.skip_download:
        print("[3/4] Downloading competition data...")
        try:
            from kaggle.downloader import download_competition_data  # type: ignore[import]
            files = download_competition_data(slug, data_dir)
            print(f"  Downloaded {len(files)} file(s):")
            for f in files:
                size_mb = f.stat().st_size / 1e6
                print(f"    {f.relative_to(root)}  ({size_mb:.2f} MB)")
        except PermissionError as e:
            print(f"[error] {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[error] Download failed: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print("[3/4] Skipping download (--skip-download).")
        if not data_dir.exists():
            print(f"[warn] data dir does not exist: {data_dir}", file=sys.stderr)

    # ------------------------------------------------------------------
    # Step 4: Inspect data schema
    # ------------------------------------------------------------------
    print("\n[4a/4] Inspecting data schema...")
    try:
        from kaggle.inspector import inspect_data_dir  # type: ignore[import]
        schema = inspect_data_dir(data_dir) if data_dir.exists() else {}
    except Exception as e:
        print(f"[warn] Schema inspection failed: {e}. Continuing with empty schema.")
        schema = {}

    for fname, s in schema.items():
        if fname.startswith("_"):
            continue
        cols = [c["name"] for c in s.get("columns", [])]
        print(f"  {fname}: {s.get('rows_in_sample', '?')} rows, columns: {cols}")

    if "_submission_format" in schema:
        sf = schema["_submission_format"]
        print(f"  Submission columns: {sf['columns']}")

    schema_path = root / "data_schema.json"
    schema_path.write_text(json.dumps(schema, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  Schema saved → {schema_path}")

    # ------------------------------------------------------------------
    # Step 4b: Generate baseline with AI
    # ------------------------------------------------------------------
    if not args.skip_baseline:
        from kaggle.baseline_gen import _DEFAULT_MODELS  # type: ignore[import]
        model_label = args.ai_model or _DEFAULT_MODELS.get(args.ai_provider, "gpt-4o")
        base_label = f" @ {args.ai_base_url}" if args.ai_base_url else ""
        print(f"\n[4b/4] Generating competition-aware baseline with {model_label}{base_label}...")
        print("       The model will first reason about the problem, then choose an approach.")
        try:
            from kaggle.baseline_gen import generate_baseline  # type: ignore[import]
            written = generate_baseline(
                competition_info=info,
                data_schema=schema,
                output_dir=root / "baseline",
                provider=args.ai_provider,
                model=args.ai_model,
                api_key=args.ai_api_key,
                base_url=args.ai_base_url,
            )
            print(f"  Generated {len(written)} file(s).")
        except EnvironmentError as e:
            print(f"[error] {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[error] Baseline generation failed: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print("\n[4b/4] Skipping baseline generation (--skip-baseline).")
        written = {}

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    _sep("Setup complete")
    print(f"  Competition info : {info_path}")
    print(f"  Data schema      : {schema_path}")
    print(f"  Data files       : {data_dir}")
    if written:
        print(f"  Baseline code    : {root / 'baseline'}")
        print(f"  AI reasoning       : {root / 'baseline' / '_reasoning.txt'}")
        print(f"\n  Review the AI's reasoning first, then run the standalone baseline:")
        print(f"    cd {root}")
        print(f"    python baseline/baseline.py")
        print(f"\n  Run AutoMLE LoRA loop:")
        safe_key = slug.replace("-", "_")
        print(f"    python run.py \\")
        print(f"        --key {safe_key} \\")
        print(f"        --checkpoint <model_id_or_path> \\")
        print(f"        --data-file {(root / 'baseline' / 'data.py').as_posix()} \\")
        print(f"        --evaluator-file {(root / 'baseline' / 'evaluator.py').as_posix()}")
    _sep()


if __name__ == "__main__":
    main()
