"""
AutoMLE Kaggle Competition Setup
=================================
Orchestrates: auth -> fetch competition info -> download data -> inspect schema -> generate baseline.

The baseline model is NOT a generic template. It is either:
  (a) written by a human who understands the competition, or
  (b) generated by Claude after reading the competition overview and data schema.

Claude's approach is chosen per-competition based on problem type, metric, and domain
knowledge — not defaulted to sklearn/XGBoost.

Usage:
    python -m kaggle.setup --competition titanic
    python -m kaggle.setup --competition house-prices-advanced-regression-techniques
    python -m kaggle.setup --competition titanic --output-dir data/titanic --skip-baseline
    python -m kaggle.setup --competition titanic --skip-download  # use existing data/

Output structure:
    <output-dir>/
    ├── competition_info.json   # title, description, metric, file list
    ├── data_schema.json        # column types, missing rates, sample values
    ├── data/                   # downloaded train.csv, test.csv, ...
    └── baseline/
        ├── baseline.py         # competition-specific model (chosen by Claude)
        ├── data.py             # AutoMLE data module (text framing for LLM fine-tuning)
        ├── evaluator.py        # AutoMLE evaluator module
        ├── _reasoning.txt      # Claude's analysis of the competition before coding
        └── _claude_response.txt

After setup, run the AutoMLE LoRA loop with:
    python run.py \\
        --key <slug> \\
        --checkpoint <model_id> \\
        --data-file <output-dir>/baseline/data.py \\
        --evaluator-file <output-dir>/baseline/evaluator.py
"""
from __future__ import annotations
import argparse
import json
import sys
from pathlib import Path


def _sep(title: str = "") -> None:
    bar = "=" * 62
    if title:
        print(f"\n{bar}\n  {title}\n{bar}")
    else:
        print(bar)


def main(argv=None) -> None:
    p = argparse.ArgumentParser(
        description="Set up an AutoMLE task from a Kaggle competition.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument(
        "--competition", required=True,
        help="Kaggle competition slug, e.g. 'titanic' or 'house-prices-advanced-regression-techniques'.",
    )
    p.add_argument(
        "--output-dir", default=None,
        help="Root directory for all outputs. Defaults to kaggle/tasks/<competition>.",
    )
    p.add_argument(
        "--skip-download", action="store_true",
        help="Skip downloading data (reuse existing files in <output-dir>/data/).",
    )
    p.add_argument(
        "--skip-baseline", action="store_true",
        help="Skip Claude baseline generation (fetch + inspect only).",
    )
    args = p.parse_args(argv)

    slug = args.competition
    root = Path(args.output_dir or f"kaggle/tasks/{slug}")
    data_dir = root / "data"

    _sep(f"Kaggle → AutoMLE : {slug}")
    print(f"  Output root : {root.resolve()}")

    # ------------------------------------------------------------------
    # Step 1: Verify Kaggle credentials
    # ------------------------------------------------------------------
    print("\n[1/4] Checking Kaggle credentials...")
    try:
        from kaggle.auth import http_auth  # type: ignore[import]
        auth = http_auth()
        print(f"  OK — authenticated as '{auth[0]}'")
    except (FileNotFoundError, ValueError) as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)

    # ------------------------------------------------------------------
    # Step 2: Fetch competition info
    # ------------------------------------------------------------------
    print("\n[2/4] Fetching competition info from Kaggle API...")
    try:
        from kaggle.fetcher import get_competition_info  # type: ignore[import]
        info = get_competition_info(slug)
    except (PermissionError, ValueError) as e:
        print(f"[error] {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"[error] Unexpected error fetching competition info: {e}", file=sys.stderr)
        sys.exit(1)

    print(f"  Title  : {info['title']}")
    print(f"  Metric : {info['evaluation_metric']}")
    print(f"  Files  : {[f['name'] for f in info['files']]}")

    root.mkdir(parents=True, exist_ok=True)
    info_path = root / "competition_info.json"
    info_path.write_text(json.dumps(info, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  Saved  → {info_path}")

    # Print overview excerpt so the user can spot-check
    desc_preview = info["description"][:500].replace("\n", " ")
    if len(info["description"]) > 500:
        desc_preview += " …"
    print(f"\n  Overview excerpt:\n    {desc_preview}\n")

    # ------------------------------------------------------------------
    # Step 3: Download data
    # ------------------------------------------------------------------
    if not args.skip_download:
        print("[3/4] Downloading competition data...")
        try:
            from kaggle.downloader import download_competition_data  # type: ignore[import]
            files = download_competition_data(slug, data_dir)
            print(f"  Downloaded {len(files)} file(s):")
            for f in files:
                size_mb = f.stat().st_size / 1e6
                print(f"    {f.relative_to(root)}  ({size_mb:.2f} MB)")
        except PermissionError as e:
            print(f"[error] {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[error] Download failed: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print("[3/4] Skipping download (--skip-download).")
        if not data_dir.exists():
            print(f"[warn] data dir does not exist: {data_dir}", file=sys.stderr)

    # ------------------------------------------------------------------
    # Step 4: Inspect data schema
    # ------------------------------------------------------------------
    print("\n[4a/4] Inspecting data schema...")
    try:
        from kaggle.inspector import inspect_data_dir  # type: ignore[import]
        schema = inspect_data_dir(data_dir) if data_dir.exists() else {}
    except Exception as e:
        print(f"[warn] Schema inspection failed: {e}. Continuing with empty schema.")
        schema = {}

    for fname, s in schema.items():
        if fname.startswith("_"):
            continue
        cols = [c["name"] for c in s.get("columns", [])]
        print(f"  {fname}: {s.get('rows_in_sample', '?')} rows, columns: {cols}")

    if "_submission_format" in schema:
        sf = schema["_submission_format"]
        print(f"  Submission columns: {sf['columns']}")

    schema_path = root / "data_schema.json"
    schema_path.write_text(json.dumps(schema, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"  Schema saved → {schema_path}")

    # ------------------------------------------------------------------
    # Step 4b: Generate baseline with Claude
    # ------------------------------------------------------------------
    if not args.skip_baseline:
        print("\n[4b/4] Generating competition-aware baseline with Claude...")
        print("       Claude will first reason about the problem, then choose an approach.")
        try:
            from kaggle.baseline_gen import generate_baseline  # type: ignore[import]
            written = generate_baseline(
                competition_info=info,
                data_schema=schema,
                output_dir=root / "baseline",
            )
            print(f"  Generated {len(written)} file(s).")
        except EnvironmentError as e:
            print(f"[error] {e}", file=sys.stderr)
            sys.exit(1)
        except Exception as e:
            print(f"[error] Baseline generation failed: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        print("\n[4b/4] Skipping baseline generation (--skip-baseline).")
        written = {}

    # ------------------------------------------------------------------
    # Summary
    # ------------------------------------------------------------------
    _sep("Setup complete")
    print(f"  Competition info : {info_path}")
    print(f"  Data schema      : {schema_path}")
    print(f"  Data files       : {data_dir}")
    if written:
        print(f"  Baseline code    : {root / 'baseline'}")
        print(f"  Claude's reasoning: {root / 'baseline' / '_reasoning.txt'}")
        print(f"\n  Review Claude's reasoning first, then run the standalone baseline:")
        print(f"    cd {root}")
        print(f"    python baseline/baseline.py")
        print(f"\n  Run AutoMLE LoRA loop:")
        safe_key = slug.replace("-", "_")
        print(f"    python run.py \\")
        print(f"        --key {safe_key} \\")
        print(f"        --checkpoint <model_id_or_path> \\")
        print(f"        --data-file {(root / 'baseline' / 'data.py').as_posix()} \\")
        print(f"        --evaluator-file {(root / 'baseline' / 'evaluator.py').as_posix()}")
    _sep()


if __name__ == "__main__":
    main()
